version: "3.9"
services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - course-service
      - quiz-service

  auth-service:
    build: ./user_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db-auth:5432/authdb
    depends_on:
      - db-auth

  course-service:
    build: ./course_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db-course:5432/coursedb
    depends_on:
      - db-course

  quiz-service:
    build: ./quiz_service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db-quiz:5432/quizdb
    depends_on:
      - db-quiz

  db-auth:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - ./data/db-auth:/var/lib/postgresql/data/pgdata

  db-course:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: coursedb
    ports:
      - "5434:5432"
    volumes:
      - ./data/db-course:/var/lib/postgresql/data/pgdata

  db-quiz:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quizdb
    ports:
      - "5435:5432"
    volumes:
      - ./data/db-quiz:/var/lib/postgresql/data/pgdata
