version: "3.9"
services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "8005:8000"
    depends_on:
      - auth-service
      - course-service
      - quiz-service
      - minio-files
    volumes:
      - ./api_gateway:/app

  auth-service:
    build: ./user_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db-auth:5432/authdb
    depends_on:
      - db-auth
    volumes:
      - ./user_service:/app

  course-service:
    build: ./course_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db-course:5432/coursedb
    depends_on:
      - db-course
      - minio-files
    volumes:
      - ./course_service:/app

  quiz-service:
    build: ./quiz_service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db-quiz:5432/quizdb
    depends_on:
      - db-quiz
    volumes:
      - ./quiz_service:/app

  s3-service:
    build: ./s3_service
    ports:
      - "8004:8000"
    depends_on:
      - db-quiz
    volumes:
      - ./s3_service:/app

  db-auth:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - ./data/db-auth:/var/lib/postgresql/data/pgdata

  db-course:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: coursedb
    ports:
      - "5434:5432"
    volumes:
      - ./data/db-course:/var/lib/postgresql/data/pgdata

  db-quiz:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quizdb
    ports:
      - "5435:5432"
    volumes:
      - ./data/db-quiz:/var/lib/postgresql/data/pgdata

  minio-files:
    image: minio/minio:latest
    container_name: minio-files
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9003"
    ports:
      - "9002:9000"     # S3 API
      - "9003:9003"     # Web-console
